### ISSUE TITLE
could not find `crossbeam_workstealing_pool` in `executors`

### ISSUE THREAD

**Issue by ramenspazz** [Bathtor/rust-executors#15]
Using the current nightly and stable toolchain of rust -- as of May 8th, 2022 -- on the example listed [here](https://docs.rs/executors/0.4.4/executors/crossbeam_workstealing_pool/index.html) results in the compiler error:
```
error[E0432]: unresolved import `executors::crossbeam_workstealing_pool`
```

My toml file includes num_cpus, crossbeam-utils, crossbeam-channel, and executors. Unless I missed something, there is some error. Also if its my error, I would suggest updating the docs page to include the correct crate to include, as it is not listed anywhere obvious if it is there,

**Comment by Bathtor** [comment]
Seems to be working fine for me.
Just created a fresh cargo executable with the following `Cargo.toml` and `main.rs`:

```toml
[package]
name = "executors-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
executors = "0.9.0"
```

```rust
use executors::*;
use executors::crossbeam_workstealing_pool;
use std::sync::mpsc::channel;

fn main() {
    let n_workers = 4;
    let n_jobs = 8;
    let pool = crossbeam_workstealing_pool::small_pool(n_workers);

    let (tx, rx) = channel();
    for _ in 0..n_jobs {
        let tx = tx.clone();
        pool.execute(move|| {
            tx.send(1).expect("channel will be there waiting for the pool");
        });
    }

    assert_eq!(rx.iter().take(n_jobs).fold(0, |a, b| a + b), 8);
    println!("Ok");
}
```
